### ISSUE TITLE
Gym-uds build in MacOS

### ISSUE THREAD

**Issue by rval735** [integeruser/gym-uds-api#1]
Today I cloned your project in a MacOS environment, when the command ```./build.sh``` was executed, it showed one error:

```
gym-uds-api$./build.sh 
./build.sh: line 2: realpath: command not found
usage: dirname path
```
Then another:
```
protoc not found!
```
Both were installed using **brew**:
```
brew install coreutils
brew install protobuf
```
Then, I had to install as well grpc for [Python](https://grpc.io/docs/quickstart/python.html) and [C++](https://github.com/grpc/grpc/blob/master/BUILDING.md)

With all that, ```build.sh``` ran effectively. 

Well, after all that, I just wanted to share the experience and possibly add as a note in the **README.md** a more explicit list in the **Requirements** section.

Or simply, just take the contents of the **binding-cpp** folder as is.

**Comment by integeruser** [comment]
Thanks for reporting! Should be fixed in e495c9a723d90739eb3df7d1ad8ac8b0b7f22006. Feel free to reopen the issue if something is still wrong.
