### ISSUE TITLE
Support for `action_t` as vector

### ISSUE THREAD

**Issue by rval735** [integeruser/gym-uds-api#2]
Is there any projected support for multiple values in the **action** part of the message along with floating/double values??

This would be useful for other environments like BipedalWalker or Video games.

If anything, I could offer to do it, however, is there any good tutorial on protobuf?? I have a hard time understanding the part:
```
serialized_pb=_b('\n\rgym-uds.proto\"\x07\n\x05\x45mpty\"H\n\x05State\x12!\n\x0bobservation\x18\x01 \x01(\x0b\x32\x0c.Observation\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"*\n\x0bObservation\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\"\x17\n\x06\x41\x63tion\x12\r\n\x05value\x18\x01 \x01(\x05\x32`\n\x0b\x45nvironment\x12\x19\n\x05Reset\x12\x06.Empty\x1a\x06.State\"\x00\x12\x19\n\x04Step\x12\x07.Action\x1a\x06.State\"\x00\x12\x1b\n\x06Sample\x12\x06.Empty\x1a\x07.Action\"\x00\x62\x06proto3')
```
Because I tried to change from int32 to double, but still the server would fail at `assert(status.ok())`  inside `EnvironmentClient::step`

**Comment by rval735** [comment]
Made some modifications in this commit:
https://github.com/rval735/gym-uds-api/commit/f8a84a6a01971063a75187e6fa1e8ef8a259a374

**Comment by integeruser** [comment]
It has been a while since I worked on this and I don't remember exactly why I did not implement actions as vectors (it was probably related to performances, but it may work for your use case). I am not going to add this anytime soon, if ever; I suggest you to fork the repo and continue the development. I appreciate your interest in the project! 🙂

**Comment by integeruser** [comment]
And for Protocol Buffers, read the [official guides](https://developers.google.com/protocol-buffers/docs/overview)!
